services:
  traefik:
    image: traefik:v3.6.2
    container_name: traefik-nseven
    restart: always
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
      - target: 443
        published: ${HTTPS_PORT:-443}
      - target: 8080 # The Web UI (enabled by --api)
        published: ${TRAEFIK_WEB_UI_PORT:-8080}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro" # linux
      - $PWD/etc_traefik:/etc/traefik
      - $PWD/certs:/certs:ro
    networks:
      - traefik-nseven

networks:
  traefik-nseven:
    external: true
