services:
  traefik:
    image: traefik:v2.10
    container_name: traefik-nseven
    restart: always
    ports:
      - target: 80
        published: ${HTTP_PORT:-80}
      - target: 443
        published: ${HTTPS_PORT:-443}
      - target: 8080
        published: ${TRAEFIK_WEB_UI_PORT:-8080}
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./traefik.yml:/etc/traefik/traefik.yml"
      - "./letsencrypt:/letsencrypt"
    command:
      - "--configFile=/etc/traefik/traefik.yml"
    networks:
      - traefik-nseven

networks:
  traefik-nseven:
    external: true
